### ISSUE TITLE
[DaughterBoard] Invalid use of blind vias

### ISSUE THREAD

**Issue by hasithvm** [rdnelson/Proxima#5]
The board house (OSHPark) does *not* support blind vias. The RF wave guide and power planes need to be redone.

See: http://support.oshpark.com/support/articles/4000019710-eagle-design-rule-files

As a plus, this allows the submission of the daughterboard to the alternate fabrication service.

**Comment by rdnelson** [comment]
@hasithvm has this been completed?

**Comment by hasithvm** [comment]
Yeah, I had to for OSH to be able to build r1.1
